// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmUbSJWGKbUmcYU2X76BX5CMCTpFfyLMA',
    appId: '1:417544481776:web:ad66fe12859a83b6fe8b35',
    messagingSenderId: '417544481776',
    projectId: 'smartbuysenegal',
    authDomain: 'smartbuysenegal.firebaseapp.com',
    storageBucket: 'smartbuysenegal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAYpIkgm_JkSOj-QAswW-J5gSJk9iRzRo',
    appId: '1:417544481776:android:f528491439d3537cfe8b35',
    messagingSenderId: '417544481776',
    projectId: 'smartbuysenegal',
    storageBucket: 'smartbuysenegal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWVhhRntEpGIUJdSox46enuc-T7zK1zJI',
    appId: '1:417544481776:ios:ac9803f7520f92e7fe8b35',
    messagingSenderId: '417544481776',
    projectId: 'smartbuysenegal',
    storageBucket: 'smartbuysenegal.firebasestorage.app',
    iosBundleId: 'com.example.smartbuySenegal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWVhhRntEpGIUJdSox46enuc-T7zK1zJI',
    appId: '1:417544481776:ios:ac9803f7520f92e7fe8b35',
    messagingSenderId: '417544481776',
    projectId: 'smartbuysenegal',
    storageBucket: 'smartbuysenegal.firebasestorage.app',
    iosBundleId: 'com.example.smartbuySenegal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmUbSJWGKbUmcYU2X76BX5CMCTpFfyLMA',
    appId: '1:417544481776:web:bea9389d8c29ee41fe8b35',
    messagingSenderId: '417544481776',
    projectId: 'smartbuysenegal',
    authDomain: 'smartbuysenegal.firebaseapp.com',
    storageBucket: 'smartbuysenegal.firebasestorage.app',
  );
}
